spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futS3
    username: postgres
    password: admin

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: true
    open-in-view: true

secret:
  key: "4e38565f12ff76de5e133eeac0085d7b842c8237117bbac10072ef79f1ca7c01"

admin:
  username: adminFutS3
  password: adminFutS3@ADMIN

userTest:
  username: userTestFutS3
  password: userTestFutS3@USER
