server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futs3db?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: admin

  flyway:
    enabled: true

  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 2MB

security:
  jwt:
    token:
      secret-key: 4e38565f12ff76de5e133eeac0085d7b842c8237117bbac10072ef79f1ca7c01
      expire-lenght: 3600000
