server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futs3db?useTimezone=true&serverTimezone=UTC
    username: postgres
    password: admin

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: true
    open-in-view: false

secret:
  key: 4e38565f12ff76de5e133eeac0085d7b842c8237117bbac10072ef79f1ca7c01

admin:
  username: admin
  password: admin@FutS3

userTest:
  username: userTest
  password: userTest@FutS3
