spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futS3
    username: postgres
    password: admin

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            "[non_contextual_creation]": true
        "[format_sql]": true
    show-sql: true
    open-in-view: true
