INSERT INTO tb_player
    (name, age, height, team, position_id)
VALUES
    -- ATACANTES
    ('Diego Souza', NULL, NULL, 'Sport Recife', 1),
    ('Edinho', NULL, NULL, 'Sport Recife', 1),
    ('Edison Negueba', NULL, NULL, 'Sport Recife', 1),
    ('Fabrício Daniel', NULL, NULL, 'Sport Recife', 1),
    ('Facundo Labandeira', 27, 173, 'Sport Recife', 1),
    ('Gabriel Santos', NULL, NULL, 'Sport Recife', 1),
    ('Gean Carlos', NULL, NULL, 'Sport Recife', 1),
    ('Michael Lima', NULL, NULL, 'Sport Recife', 1),
    ('Peglow', NULL, NULL, 'Sport Recife', 1),
    ('Vagner Love', 39, 172, 'Sport Recife', 1),
    ('Wanderson', 35, 167, 'Sport Recife', 1),

    -- GOLEIRO
    ('Adriano', NULL, NULL, 'Sport Recife', 3),
    ('Denis', NULL, NULL, 'Sport Recife', 3),
    ('Denival', 23, 203, 'Sport Recife', 3),
    ('Jordan', NULL, NULL, 'Sport Recife', 3),
    ('Renan', NULL, NULL, 'Sport Recife', 3),

    -- LATERAL DIREITO
    ('Eduardo', NULL, NULL, 'Sport Recife', 4),
    ('Everton', 23, 171, 'Sport Recife', 4),
    ('Felipinho', 19, 182, 'Sport Recife', 4),
    ('Igor Cariús', NULL, NULL, 'Sport Recife', 4),
    ('Nathan', NULL, NULL, 'Sport Recife', 4),
    ('Roberto Rosales', NULL, NULL, 'Sport Recife', 4),
    ('Victor Gabriel', NULL, NULL, 'Sport Recife', 4),

    -- MEIA DIREITO
    ('Alan Ruiz', NULL, NULL, 'Sport Recife', 7),
    ('Jorginho', NULL, NULL, 'Sport Recife', 7),
    ('Juan Xavier', NULL, NULL, 'Sport Recife', 7),

    -- PRIMEIRO VOLANTE
    ('Fabinho', NULL, NULL, 'Sport Recife', 9),
    ('Felipe', NULL, NULL, 'Sport Recife', 9),
    ('Fábio Matheus', NULL, NULL, 'Sport Recife', 9),
    ('Lucas André', NULL, NULL, 'Sport Recife', 9),
    ('Pedro Martins', 23, 175, 'Sport Recife', 9),
    ('Ronaldo', 29, 172, 'Sport Recife', 9),

    -- ZAGUEIRO DESTRO
    ('Alisson Cassiano', NULL, NULL, 'Sport Recife', 15),
    ('Chico', 25, 188, 'Sport Recife', 15),
    ('Matheus Baraka', NULL, NULL, 'Sport Recife', 15),
    ('Rafael Thyere', 30, 189, 'Sport Recife', 15),
    ('Renzo', 22, 184, 'Sport Recife', 15),
    ('Sabino', 27, 189, 'Sport Recife', 15),

    -- MOCK
    ('Inglebert', 82, NULL, 'Bahia', 12),
    ('Clayborn', NULL, 140, 'Atlético Mineiro', 4),
    ('Carly', NULL, 237, 'Athletico Paranaense', 5),
    ('Reggis', 44, NULL, 'Avaí', 12),
    ('Jarvis', NULL, 187, 'Atlético Mineiro', 9),
    ('Niven', NULL, NULL, 'Vasco', 1),
    ('Hilarius', NULL, NULL, 'Avaí', 15),
    ('Sylvester', NULL, 213, 'Internacional', 13),
    ('Lennie', 15, NULL, 'Fluminense', 11),
    ('Fredrick', 93, NULL, 'Grêmio', 4),
    ('Matthiew', NULL, NULL, 'Internacional', 6),
    ('Bernarr', NULL, NULL, 'Fluminense', 15),
    ('Jesus', NULL, 91, 'São Paulo', 5),
    ('Patrice', 79, 171, 'Cruzeiro', 13),
    ('Balduin', 141, NULL, 'Corinthians', 1),
    ('Carmine', NULL, NULL, 'Internacional', 13),
    ('Heywood', 79, NULL, 'Goiás', 14),
    ('Feodor', 4, NULL, 'Avaí', 9),
    ('Mendie', 96, 169, 'Grêmio', 6),
    ('Parry', NULL, 250, 'Cruzeiro', 8),
    ('Elia', NULL, 102, 'Botafogo', 8),
    ('Carney', 96, 100, 'Santos', 12),
    ('Prentiss', 93, 172, 'Santos', 15),
    ('Dieter', NULL, NULL, 'Botafogo', 7),
    ('Mattheus', 139, NULL, 'Fortaleza', 5),
    ('Mateo', 14, NULL, 'Fortaleza', 10),
    ('Temple', NULL, 184, 'Athletico Paranaense', 11),
    ('Zolly', NULL, 179, 'Athletico Paranaense', 3),
    ('Roth', 117, 70, 'Atlético Mineiro', 2),
    ('Ben', NULL, 65, 'Bahia', 4),
    ('Rolf', 91, 228, 'São Paulo', 1),
    ('Nehemiah', 71, NULL, 'Ceará', 10),
    ('Kingsly', NULL, 164, 'Ceará', 8),
    ('Conroy', NULL, 218, 'Botafogo', 3),
    ('Felike', NULL, 77, 'Internacional', 15),
    ('Neddy', NULL, NULL, 'Bahia', 3),
    ('Torre', 92, 135, 'São Paulo', 14),
    ('Orville', NULL, NULL, 'Avaí', 2),
    ('Ricardo', 2, NULL, 'Botafogo', 13),
    ('Andre', NULL, NULL, 'Vasco', 14),
    ('Noble', 15, NULL, 'Avaí', 9),
    ('Yale', NULL, NULL, 'Vasco', 13),
    ('Chane', 67, NULL, 'Ceará', 13),
    ('Gray', 102, 212, 'Grêmio', 7),
    ('Reuben', 35, NULL, 'Internacional', 9),
    ('Berke', NULL, NULL, 'Botafogo', 12),
    ('Donnell', 70, 113, 'Chapecoense', 4),
    ('Merwin', 136, NULL, 'Avaí', 6),
    ('Georges', 80, NULL, 'Santos', 13),
    ('Rhett', NULL, 129, 'Santos', 3),
    ('Any', NULL, 91, 'Palmeiras', 9),
    ('Elden', NULL, NULL, 'São Paulo', 5),
    ('Hilario', NULL, 189, 'Cruzeiro', 3),
    ('Neel', NULL, 183, 'Athletico Paranaense', 3),
    ('Rooney', 91, NULL, 'Botafogo', 14),
    ('George', NULL, NULL, 'Cruzeiro', 14),
    ('Felice', NULL, NULL, 'Avaí', 12),
    ('Kaleb', 75, 129, 'Corinthians', 5),
    ('Winthrop', 10, 74, 'Atlético Mineiro', 14),
    ('Victor', 78, 161, 'Atlético Mineiro', 13),
    ('Raul', NULL, 96, 'Grêmio', 10),
    ('Caz', 131, 136, 'Sport Recife', 11),
    ('Harold', 135, NULL, 'Ceará', 15),
    ('Giffer', 72, NULL, 'São Paulo', 2),
    ('Dickie', 26, 176, 'Fortaleza', 11),
    ('Clemmy', 146, 185, 'Chapecoense', 7),
    ('Ruddie', NULL, 176, 'Fluminense', 1),
    ('Samuele', 101, 108, 'Botafogo', 6),
    ('Farley', 29, 101, 'Grêmio', 4),
    ('Stu', 119, 70, 'Chapecoense', 2),
    ('Ado', NULL, NULL, 'Chapecoense', 11),
    ('Nigel', NULL, 182, 'Botafogo', 1),
    ('Quinn', 127, 142, 'São Paulo', 1),
    ('Hugibert', 5, NULL, 'Fortaleza', 4),
    ('Stephen', 114, NULL, 'Flamengo', 2),
    ('Arnuad', NULL, 181, 'Fortaleza', 2),
    ('Floyd', 136, 165, 'Chapecoense', 10),
    ('Harlen', 105, NULL, 'Fortaleza', 14),
    ('Aubert', 24, NULL, 'Ceará', 7),
    ('Giusto', 69, NULL, 'Goiás', 13),
    ('Cyrus', NULL, 126, 'Botafogo', 3),
    ('Loren', 34, NULL, 'Internacional', 13),
    ('Alvan', NULL, 194, 'Flamengo', 1),
    ('Eamon', 124, NULL, 'Grêmio', 4),
    ('Avery', NULL, 69, 'Flamengo', 12),
    ('Lawrence', 47, NULL, 'Athletico Paranaense', 14),
    ('Armin', NULL, 161, 'Cruzeiro', 2),
    ('Ellis', 135, NULL, 'Internacional', 14),
    ('Hilary', NULL, NULL, 'Cruzeiro', 14),
    ('Lammond', NULL, 185, 'Avaí', 8),
    ('Nickolai', NULL, 140, 'Cruzeiro', 10),
    ('See', NULL, NULL, 'Sport Recife', 9),
    ('Hillier', NULL, NULL, 'Corinthians', 4),
    ('Jake', NULL, NULL, 'Internacional', 5),
    ('Caleb', 110, 87, 'Fortaleza', 13),
    ('Alfie', NULL, 105, 'Goiás', 8),
    ('Rollo', NULL, NULL, 'Vasco', 5),
    ('Georgie', NULL, NULL, 'Fortaleza', 7),
    ('Ivan', 117, NULL, 'Bahia', 8),
    ('Nikolos', NULL, 242, 'Goiás', 9),
    ('Olenolin', 95, 211, 'Fluminense', 8),
    ('Vern', NULL, NULL, 'Santos', 11),
    ('Normy', 94, 168, 'Chapecoense', 3),
    ('Janos', 48, 215, 'Avaí', 7),
    ('Gardener', 87, NULL, 'Ceará', 14),
    ('Maurits', 47, 229, 'Internacional', 3),
    ('Heinrik', 142, 161, 'Palmeiras', 12),
    ('Wake', NULL, 185, 'São Paulo', 12),
    ('Flin', 26, 245, 'Grêmio', 13),
    ('Noah', 57, 151, 'Avaí', 13),
    ('Baxie', NULL, NULL, 'São Paulo', 12),
    ('Andrew', 21, 147, 'Avaí', 15),
    ('Ransom', NULL, 93, 'São Paulo', 12),
    ('Gayle', 140, NULL, 'Flamengo', 15),
    ('Shawn', 111, NULL, 'Atlético Mineiro', 15),
    ('Isadore', NULL, 168, 'Ceará', 1),
    ('Andrey', 58, NULL, 'Bahia', 7),
    ('Tedman', 112, NULL, 'Cruzeiro', 14),
    ('Karim', 119, 219, 'Chapecoense', 5),
    ('Will', NULL, 148, 'Ceará', 3),
    ('Alva', 98, 166, 'Fortaleza', 5),
    ('Engelbert', NULL, NULL, 'Internacional', 4),
    ('Anthony', 37, 191, 'Bahia', 6),
    ('Gallard', 122, NULL, 'Cruzeiro', 3),
    ('Ryon', 33, 149, 'Grêmio', 2),
    ('Nikola', NULL, 166, 'Cruzeiro', 9),
    ('Lucas', 107, 99, 'Bahia', 6),
    ('Rafaello', NULL, 98, 'Avaí', 13),
    ('Danny', NULL, NULL, 'Fluminense', 12),
    ('Brade', NULL, NULL, 'Athletico Paranaense', 3),
    ('Garold', NULL, NULL, 'Atlético Mineiro', 3),
    ('Raffaello', 59, 241, 'Vasco', 1),
    ('Gherardo', 81, NULL, 'Bahia', 13),
    ('Etan', 128, NULL, 'Botafogo', 1),
    ('Cornelius', 100, NULL, 'Bahia', 1),
    ('Nevil', 133, NULL, 'Goiás', 11),
    ('Sigmund', 122, 127, 'Ceará', 11),
    ('Giffie', NULL, 84, 'Internacional', 4),
    ('Freemon', NULL, 186, 'Ceará', 11),
    ('Bartie', 141, NULL, 'Goiás', 13),
    ('Perkin', 102, 77, 'Grêmio', 6),
    ('Marlon', NULL, 206, 'Cruzeiro', 12),
    ('Angus', NULL, 113, 'Palmeiras', 13),
    ('Aleksandr', NULL, 199, 'Palmeiras', 3),
    ('Hamel', NULL, 159, 'Ceará', 1),
    ('Durward', NULL, 216, 'Palmeiras', 9),
    ('Arch', NULL, NULL, 'Sport Recife', 6),
    ('Perkin', 101, 109, 'Fluminense', 13),
    ('Darius', 131, NULL, 'Cruzeiro', 7),
    ('Niki', 123, 217, 'Botafogo', 13),
    ('Brucie', NULL, NULL, 'Palmeiras', 14),
    ('Staford', 137, 79, 'Atlético Mineiro', 2),
    ('Giacopo', 93, NULL, 'Fluminense', 15),
    ('Jonathan', NULL, 185, 'Santos', 6),
    ('Gustavus', NULL, NULL, 'Grêmio', 12),
    ('Stuart', NULL, NULL, 'Fortaleza', 9),
    ('Terrel', 58, NULL, 'Sport Recife', 1),
    ('Benjamen', 25, NULL, 'Fluminense', 5),
    ('Chad', NULL, NULL, 'Grêmio', 8),
    ('Vail', NULL, 93, 'Atlético Mineiro', 12),
    ('Drud', 31, 244, 'São Paulo', 1),
    ('Maximo', NULL, 194, 'Athletico Paranaense', 10),
    ('Odey', NULL, 222, 'Goiás', 14),
    ('Robby', NULL, 114, 'Flamengo', 6),
    ('Nickie', 125, 70, 'São Paulo', 1),
    ('Halsey', NULL, 163, 'Bahia', 12),
    ('Justin', 72, 102, 'Atlético Mineiro', 14),
    ('Burtie', 104, NULL, 'Fortaleza', 14),
    ('Christophe', 35, NULL, 'São Paulo', 7),
    ('Bill', NULL, 194, 'Atlético Mineiro', 3),
    ('Izzy', NULL, NULL, 'Ceará', 10),
    ('Humbert', 96, 148, 'Athletico Paranaense', 9),
    ('Chic', 45, NULL, 'Flamengo', 2),
    ('Josiah', 135, NULL, 'São Paulo', 14),
    ('Elston', NULL, 192, 'Cruzeiro', 10),
    ('Sergeant', 102, NULL, 'Corinthians', 4),
    ('Willi', NULL, NULL, 'Fluminense', 1),
    ('Marlin', 124, NULL, 'Sport Recife', 6),
    ('Verge', NULL, 239, 'Atlético Mineiro', 2),
    ('Culver', NULL, NULL, 'Ceará', 11),
    ('Harold', 102, 100, 'Sport Recife', 4),
    ('Frankie', NULL, 114, 'Fortaleza', 12),
    ('Moise', NULL, 119, 'Fortaleza', 11),
    ('Paulo', NULL, NULL, 'Santos', 1),
    ('Ogdon', 136, 176, 'Vasco', 6),
    ('Jocko', 98, NULL, 'Internacional', 3),
    ('Waldo', NULL, NULL, 'Botafogo', 11),
    ('Scarface', 44, NULL, 'Palmeiras', 3),
    ('Barnaby', 137, 152, 'Ceará', 5),
    ('Ichabod', NULL, NULL, 'Athletico Paranaense', 15),
    ('Miltie', 131, 229, 'Goiás', 5),
    ('Cy', NULL, NULL, 'Santos', 11),
    ('Merell', 2, NULL, 'Flamengo', 4),
    ('Burnard', NULL, NULL, 'Bahia', 10),
    ('Reidar', NULL, 172, 'Ceará', 2),
    ('Hal', 27, NULL, 'Avaí', 11),
    ('Rudolf', 14, 230, 'Avaí', 1),
    ('Shep', NULL, 120, 'Avaí', 5),
    ('Maxwell', 47, 113, 'Chapecoense', 10),
    ('Kingsly', 14, 109, 'Goiás', 13),
    ('Kurt', 19, 158, 'Corinthians', 4),
    ('Xavier', NULL, NULL, 'Grêmio', 7),
    ('Dennison', NULL, 123, 'Ceará', 2),
    ('Pryce', NULL, 165, 'Grêmio', 12),
    ('Gregoor', NULL, NULL, 'Ceará', 1),
    ('Isaiah', 66, NULL, 'Bahia', 15),
    ('Ugo', NULL, NULL, 'Fluminense', 7),
    ('Hastings', NULL, 243, 'Chapecoense', 8),
    ('Gilburt', NULL, 184, 'Corinthians', 4),
    ('Binky', NULL, 239, 'Bahia', 12),
    ('Ashley', NULL, NULL, 'São Paulo', 4),
    ('Josiah', 114, 189, 'Chapecoense', 6),
    ('Blake', NULL, 126, 'Goiás', 8),
    ('Worth', 130, NULL, 'Botafogo', 7),
    ('Rogerio', 108, NULL, 'São Paulo', 1),
    ('Bradford', 132, NULL, 'Chapecoense', 1),
    ('Perceval', NULL, 166, 'Chapecoense', 15),
    ('Earl', 117, 215, 'Flamengo', 7),
    ('Scotti', NULL, 140, 'Ceará', 5),
    ('Samson', 62, NULL, 'Sport Recife', 6),
    ('Thorny', 68, 226, 'Vasco', 3),
    ('Harwilll', 40, 163, 'Bahia', 6),
    ('Dalis', 124, 157, 'Bahia', 14),
    ('Morten', NULL, 250, 'Corinthians', 10),
    ('Benn', NULL, 114, 'Cruzeiro', 14),
    ('Nick', 55, NULL, 'Bahia', 5),
    ('Tonnie', NULL, 187, 'Cruzeiro', 3),
    ('Gay', NULL, NULL, 'Santos', 12),
    ('Everett', NULL, 97, 'São Paulo', 13),
    ('Stephanus', NULL, NULL, 'Flamengo', 12),
    ('Prinz', 38, NULL, 'Sport Recife', 3),
    ('Michal', 12, NULL, 'Santos', 14),
    ('Rik', 24, 143, 'Fortaleza', 10),
    ('Merle', 123, NULL, 'Santos', 10),
    ('Teodor', 25, NULL, 'Fortaleza', 11),
    ('Kain', 137, NULL, 'Chapecoense', 4),
    ('Abbie', NULL, 158, 'São Paulo', 11),
    ('Arlan', 15, 128, 'São Paulo', 12),
    ('Huberto', 108, NULL, 'Cruzeiro', 2),
    ('Nappie', 92, 165, 'São Paulo', 8),
    ('Colas', 114, 128, 'Atlético Mineiro', 15),
    ('Zaccaria', 128, 217, 'Internacional', 8),
    ('Kingsley', NULL, NULL, 'Avaí', 14),
    ('Barnabe', 133, 217, 'Fortaleza', 9),
    ('Ingelbert', 106, NULL, 'Botafogo', 14),
    ('Fraze', 15, NULL, 'Fluminense', 14),
    ('Merry', 101, NULL, 'Avaí', 6),
    ('Sutherlan', NULL, NULL, 'Internacional', 15),
    ('Jakob', 69, 205, 'Corinthians', 15),
    ('Thain', NULL, NULL, 'Flamengo', 5),
    ('Maddy', 129, 100, 'Botafogo', 3),
    ('Filmer', 32, 218, 'Bahia', 2),
    ('Frankie', 95, 209, 'Avaí', 13),
    ('Olav', 18, NULL, 'São Paulo', 15),
    ('Jordan', NULL, NULL, 'Atlético Mineiro', 13),
    ('Omar', 91, NULL, 'Athletico Paranaense', 2),
    ('Nicola', NULL, 143, 'Avaí', 3),
    ('Daven', 117, 103, 'Atlético Mineiro', 12),
    ('Meir', NULL, NULL, 'Internacional', 15),
    ('Flint', 116, 212, 'Botafogo', 3),
    ('Lane', NULL, 90, 'Fluminense', 14),
    ('Daren', NULL, 135, 'Vasco', 4),
    ('Alfredo', NULL, NULL, 'Sport Recife', 1),
    ('Adolphus', NULL, NULL, 'São Paulo', 13),
    ('Andrea', 69, NULL, 'Bahia', 14),
    ('Wilt', NULL, 125, 'Flamengo', 7),
    ('Stephen', 14, 117, 'Ceará', 4),
    ('Lemuel', NULL, 192, 'São Paulo', 6),
    ('Reinald', NULL, NULL, 'Internacional', 15),
    ('Reynolds', 149, NULL, 'Bahia', 10),
    ('Edouard', 21, NULL, 'Corinthians', 6),
    ('Wells', NULL, 218, 'Atlético Mineiro', 8),
    ('Giusto', 143, NULL, 'Corinthians', 10),
    ('Hallsy', 62, 211, 'Santos', 2),
    ('Virgie', 87, 83, 'Fortaleza', 8),
    ('Rhys', NULL, 128, 'Flamengo', 6),
    ('Alon', 124, NULL, 'Avaí', 7),
    ('Emmerich', 140, NULL, 'Grêmio', 5),
    ('Bearnard', NULL, NULL, 'Fortaleza', 12),
    ('Melvin', 35, NULL, 'Corinthians', 11),
    ('Granthem', 21, 94, 'Flamengo', 12),
    ('Ivan', 30, 126, 'Goiás', 3),
    ('Christie', 130, 180, 'Chapecoense', 7),
    ('Darius', 74, 234, 'Santos', 11),
    ('Mickey', 137, NULL, 'Internacional', 9),
    ('Colet', 71, NULL, 'Chapecoense', 13),
    ('Costa', 20, 98, 'Vasco', 13),
    ('Niall', NULL, 235, 'Bahia', 11),
    ('Yuri', 93, NULL, 'Cruzeiro', 7),
    ('Lanny', 145, 162, 'Avaí', 11),
    ('Torey', 78, 153, 'Fortaleza', 1),
    ('Kenyon', 148, 212, 'Santos', 12),
    ('Conny', 12, 171, 'Santos', 4),
    ('Royal', 51, NULL, 'Vasco', 14),
    ('Arnuad', 91, 162, 'Internacional', 14),
    ('Oliviero', NULL, NULL, 'Chapecoense', 11),
    ('Peyton', 76, NULL, 'Ceará', 7),
    ('Jabez', 125, 66, 'Flamengo', 6),
    ('Anton', 88, 144, 'Sport Recife', 8),
    ('Buck', 54, NULL, 'Sport Recife', 5),
    ('Peyton', 30, 149, 'Cruzeiro', 5),
    ('Dorey', NULL, 210, 'Bahia', 12),
    ('Hamish', 76, NULL, 'Avaí', 1),
    ('Chaunce', 68, NULL, 'Chapecoense', 6),
    ('Ozzie', NULL, NULL, 'Avaí', 11),
    ('Byrann', NULL, 117, 'Athletico Paranaense', 11),
    ('Dukie', 22, NULL, 'Flamengo', 9),
    ('Harley', 62, NULL, 'Santos', 1),
    ('Beck', NULL, NULL, 'Fortaleza', 12),
    ('Lamont', NULL, 219, 'Santos', 4),
    ('Vlad', 40, NULL, 'Ceará', 6),
    ('Casey', 79, NULL, 'Cruzeiro', 9),
    ('Neal', 49, NULL, 'Internacional', 6),
    ('Harwell', 66, 228, 'Cruzeiro', 1),
    ('Jeddy', 91, 160, 'Atlético Mineiro', 2),
    ('Gerard', 126, 202, 'Athletico Paranaense', 5),
    ('Artair', NULL, 233, 'Grêmio', 5),
    ('Dunn', 87, 224, 'Atlético Mineiro', 5),
    ('Kevin', 85, 70, 'São Paulo', 8),
    ('Andrej', NULL, 212, 'Ceará', 8),
    ('Corbin', NULL, NULL, 'Atlético Mineiro', 9),
    ('Dennet', 33, 173, 'Internacional', 8),
    ('Nahum', 10, 131, 'Atlético Mineiro', 11),
    ('Filmer', NULL, NULL, 'Santos', 15),
    ('Myron', NULL, NULL, 'Atlético Mineiro', 5),
    ('Hubie', 145, 141, 'Bahia', 6),
    ('Trip', NULL, 97, 'Goiás', 12),
    ('Duke', 71, 94, 'Goiás', 6),
    ('Dewain', NULL, 153, 'Internacional', 2),
    ('Clyve', 33, NULL, 'Corinthians', 9),
    ('Phil', 112, NULL, 'Ceará', 3),
    ('Augusto', 136, NULL, 'Corinthians', 12),
    ('Simmonds', NULL, 180, 'Avaí', 13),
    ('Jerrie', 137, 214, 'Ceará', 10),
    ('Aubrey', NULL, NULL, 'Vasco', 2),
    ('Stavros', 21, NULL, 'Ceará', 7),
    ('Mannie', 130, NULL, 'Athletico Paranaense', 2),
    ('De witt', 96, NULL, 'Fluminense', 2),
    ('Aubert', NULL, 66, 'Vasco', 8),
    ('Gabriello', 19, 158, 'Grêmio', 14),
    ('Irv', NULL, NULL, 'Fortaleza', 4),
    ('Donaugh', 69, 196, 'Internacional', 4),
    ('Wynn', 97, 84, 'Vasco', 7),
    ('Arri', 83, 69, 'Chapecoense', 11),
    ('Lothario', 42, 74, 'Bahia', 7),
    ('Wait', 107, 225, 'Grêmio', 8),
    ('Gran', 147, NULL, 'Atlético Mineiro', 7),
    ('Martin', 53, NULL, 'São Paulo', 6),
    ('Arri', 44, 200, 'Santos', 8),
    ('Giffer', 106, 180, 'Chapecoense', 4),
    ('Siffre', 106, NULL, 'Grêmio', 10),
    ('Rollin', 64, 92, 'Atlético Mineiro', 9),
    ('Ingra', 136, 122, 'Santos', 11),
    ('Renado', NULL, NULL, 'Avaí', 11),
    ('Boyce', NULL, NULL, 'Bahia', 9),
    ('Kennett', 31, NULL, 'Ceará', 14),
    ('Finley', NULL, 233, 'Botafogo', 12),
    ('Alden', 128, 80, 'Vasco', 14),
    ('Wally', 23, NULL, 'Bahia', 5),
    ('Barnebas', 147, NULL, 'Grêmio', 5),
    ('Chilton', NULL, 237, 'Goiás', 3),
    ('Trevar', 29, NULL, 'Palmeiras', 7),
    ('Pavel', 93, NULL, 'Athletico Paranaense', 14),
    ('Andre', NULL, 136, 'Fortaleza', 3),
    ('Aldridge', 97, NULL, 'Atlético Mineiro', 5),
    ('Francisco', 133, NULL, 'Grêmio', 6),
    ('Cosmo', 138, 148, 'Atlético Mineiro', 12),
    ('Bartholomew', NULL, NULL, 'Bahia', 8),
    ('Esteban', NULL, 146, 'Internacional', 8),
    ('Steve', NULL, NULL, 'Santos', 2),
    ('Ruttger', NULL, 181, 'Vasco', 15),
    ('Ozzy', NULL, 112, 'Bahia', 9),
    ('Palmer', 61, 96, 'Internacional', 14),
    ('Hadleigh', NULL, NULL, 'Palmeiras', 4),
    ('Shaun', 95, 248, 'Bahia', 9),
    ('Lind', 40, 201, 'Fluminense', 13),
    ('Thornie', NULL, 241, 'Fluminense', 11),
    ('Cord', 103, 234, 'Ceará', 7),
    ('Tirrell', NULL, NULL, 'Chapecoense', 9),
    ('Efren', NULL, NULL, 'Avaí', 12),
    ('Huntlee', 39, NULL, 'Grêmio', 10),
    ('Bronny', NULL, 110, 'Botafogo', 6),
    ('Hastie', 93, 142, 'Palmeiras', 8),
    ('Dael', NULL, NULL, 'Corinthians', 12),
    ('Ahmad', NULL, NULL, 'Internacional', 9),
    ('Dewain', 130, NULL, 'Chapecoense', 9),
    ('Derwin', NULL, 90, 'Palmeiras', 1),
    ('Jefferey', NULL, NULL, 'Corinthians', 15),
    ('Elton', 97, NULL, 'Bahia', 10),
    ('Patrice', 42, 66, 'Ceará', 3),
    ('Timothy', 32, 137, 'Flamengo', 5),
    ('Wash', NULL, 240, 'Grêmio', 4),
    ('Wilt', 11, NULL, 'Santos', 14),
    ('Hilario', NULL, NULL, 'Santos', 15),
    ('Everard', NULL, 114, 'Bahia', 11),
    ('Conant', NULL, 126, 'Corinthians', 1),
    ('Traver', NULL, 123, 'Fluminense', 13),
    ('Ervin', NULL, 160, 'Athletico Paranaense', 14),
    ('Boone', NULL, NULL, 'Athletico Paranaense', 11),
    ('Fredric', 147, NULL, 'Avaí', 14),
    ('Pooh', 63, 112, 'Avaí', 4),
    ('Sig', NULL, 104, 'Chapecoense', 12),
    ('Raviv', 115, NULL, 'Santos', 14),
    ('Erskine', NULL, 176, 'Goiás', 1),
    ('Bendick', NULL, 182, 'Goiás', 5),
    ('Paulie', 12, NULL, 'Chapecoense', 10),
    ('Meredeth', NULL, NULL, 'Goiás', 14),
    ('Cass', NULL, 176, 'Vasco', 6),
    ('Emlyn', NULL, NULL, 'Goiás', 11),
    ('Jodie', NULL, NULL, 'Ceará', 5),
    ('Christophorus', 57, 122, 'Fluminense', 1),
    ('Toddie', 3, 115, 'Sport Recife', 5),
    ('Keane', 33, NULL, 'Avaí', 9),
    ('Ganny', NULL, NULL, 'Internacional', 9),
    ('Eben', NULL, NULL, 'Chapecoense', 1),
    ('Lovell', NULL, NULL, 'Internacional', 3),
    ('Ellerey', 139, NULL, 'Internacional', 2),
    ('Raddy', NULL, NULL, 'Ceará', 3),
    ('Taylor', NULL, 123, 'São Paulo', 7),
    ('Esra', 7, NULL, 'Goiás', 12),
    ('Stillmann', NULL, 215, 'Fluminense', 6),
    ('Tiler', NULL, 99, 'Sport Recife', 15),
    ('Jakie', NULL, NULL, 'Bahia', 10),
    ('Artemus', 68, 163, 'Atlético Mineiro', 1),
    ('Grove', 71, 131, 'Palmeiras', 2),
    ('Bentley', 63, NULL, 'Palmeiras', 13),
    ('Cornelius', 49, NULL, 'Chapecoense', 4),
    ('Barr', NULL, 144, 'Goiás', 11),
    ('Clarance', NULL, 225, 'Atlético Mineiro', 13),
    ('Darby', NULL, NULL, 'Internacional', 4),
    ('Nathanial', 147, 145, 'Corinthians', 7),
    ('Kane', 83, NULL, 'Fluminense', 1),
    ('Dmitri', NULL, 173, 'Sport Recife', 6),
    ('Buck', 145, NULL, 'Grêmio', 4),
    ('Korey', NULL, 74, 'Santos', 5),
    ('Culver', 30, 243, 'Chapecoense', 9),
    ('Scotty', NULL, NULL, 'Vasco', 2),
    ('Bil', 80, 80, 'Ceará', 11),
    ('Uriel', NULL, 107, 'Palmeiras', 14),
    ('Zolly', NULL, 250, 'Flamengo', 1),
    ('Raul', NULL, NULL, 'Chapecoense', 5),
    ('Donaugh', NULL, 144, 'Flamengo', 3),
    ('Shaw', 95, 109, 'Chapecoense', 5),
    ('Brett', 150, 214, 'Ceará', 14),
    ('Irvin', NULL, NULL, 'Fortaleza', 3),
    ('Reggis', 141, NULL, 'Fortaleza', 5),
    ('Shaughn', NULL, 158, 'Bahia', 4),
    ('Conroy', 80, NULL, 'Internacional', 2),
    ('Traver', 30, 161, 'Goiás', 2),
    ('Aleksandr', 17, 230, 'Sport Recife', 6),
    ('Dominic', 38, 245, 'Avaí', 2),
    ('Curt', 6, 160, 'Atlético Mineiro', 1),
    ('Edmund', NULL, 116, 'Internacional', 12),
    ('Packston', NULL, NULL, 'Avaí', 6),
    ('Riordan', NULL, NULL, 'Botafogo', 13),
    ('Ezekiel', NULL, 213, 'Athletico Paranaense', 4),
    ('Humbert', NULL, NULL, 'Santos', 5),
    ('Matt', NULL, NULL, 'Flamengo', 13),
    ('Sigvard', 71, NULL, 'Ceará', 9),
    ('Willard', 24, NULL, 'Cruzeiro', 9),
    ('Paul', NULL, NULL, 'Corinthians', 12),
    ('Sandor', NULL, 164, 'Sport Recife', 4),
    ('Rory', 138, NULL, 'São Paulo', 10),
    ('Marty', 137, 135, 'Chapecoense', 3),
    ('Tibold', 70, 111, 'Fluminense', 8),
    ('Loy', NULL, NULL, 'Palmeiras', 2),
    ('D''arcy', 135, NULL, 'Avaí', 11),
    ('Nils', 121, NULL, 'Santos', 9),
    ('Davey', 72, NULL, 'Goiás', 6),
    ('Sterling', 136, NULL, 'Sport Recife', 1),
    ('Galen', NULL, NULL, 'Bahia', 14),
    ('Clayton', 48, 170, 'Sport Recife', 5),
    ('Oswald', NULL, NULL, 'Cruzeiro', 6),
    ('Hymie', 17, NULL, 'Fortaleza', 15),
    ('Noby', 139, 163, 'Athletico Paranaense', 12),
    ('Kippy', NULL, 244, 'Bahia', 9),
    ('Bowie', NULL, 209, 'Grêmio', 5),
    ('Geno', 60, 184, 'Sport Recife', 8),
    ('Noby', 143, 124, 'Avaí', 11),
    ('Leland', NULL, NULL, 'Flamengo', 1),
    ('Putnam', 37, 85, 'Avaí', 15),
    ('Yanaton', 34, 197, 'Cruzeiro', 6),
    ('Emanuele', NULL, 244, 'Fortaleza', 13),
    ('Weider', 32, 166, 'Chapecoense', 6),
    ('Nefen', NULL, 66, 'Fortaleza', 13),
    ('Raynor', NULL, 229, 'Sport Recife', 12),
    ('Hi', 22, 70, 'Vasco', 15),
    ('Erny', NULL, 232, 'Fluminense', 1),
    ('Erich', 72, NULL, 'Corinthians', 15),
    ('Emmit', 84, NULL, 'Corinthians', 7),
    ('Eldon', NULL, 190, 'Goiás', 7),
    ('Eduard', 74, 147, 'Athletico Paranaense', 5),
    ('Zebulen', 67, 195, 'Cruzeiro', 5),
    ('Lyle', NULL, 200, 'Fortaleza', 15),
    ('Mitchael', NULL, NULL, 'Atlético Mineiro', 8),
    ('Gideon', NULL, 103, 'Goiás', 15),
    ('Joshuah', 62, 138, 'Palmeiras', 14),
    ('Foster', NULL, 224, 'Sport Recife', 3),
    ('Tynan', 120, 129, 'Corinthians', 1),
    ('Jacques', NULL, NULL, 'Fluminense', 9),
    ('Penny', NULL, NULL, 'Palmeiras', 15),
    ('Jarrett', NULL, NULL, 'Goiás', 3),
    ('Scotti', 10, 200, 'Goiás', 3),
    ('Francesco', NULL, NULL, 'São Paulo', 6),
    ('Herve', 37, NULL, 'Santos', 5),
    ('Arnold', NULL, NULL, 'Fortaleza', 3),
    ('Zed', 81, NULL, 'Cruzeiro', 10),
    ('Madison', 131, NULL, 'Grêmio', 14),
    ('Jae', 52, 113, 'São Paulo', 7),
    ('Job', 129, 144, 'Ceará', 7),
    ('Donavon', 61, 157, 'Ceará', 13),
    ('Kellby', NULL, 245, 'São Paulo', 9),
    ('Myrvyn', NULL, NULL, 'Fluminense', 7),
    ('Guss', 26, 180, 'Chapecoense', 8),
    ('Mic', 50, NULL, 'Santos', 6),
    ('Emmet', NULL, NULL, 'Fortaleza', 13),
    ('Ellwood', NULL, NULL, 'Palmeiras', 14),
    ('Elijah', NULL, NULL, 'Atlético Mineiro', 9),
    ('Zerk', 39, 231, 'Corinthians', 14),
    ('Westbrook', NULL, 168, 'Santos', 9),
    ('Carter', 49, NULL, 'Palmeiras', 7),
    ('Vasili', NULL, NULL, 'Goiás', 10),
    ('Fee', NULL, NULL, 'Cruzeiro', 14),
    ('Kain', NULL, NULL, 'Goiás', 1),
    ('Archer', 112, 127, 'Athletico Paranaense', 15),
    ('Chickie', NULL, 133, 'Flamengo', 5),
    ('Ragnar', 7, 239, 'Flamengo', 11),
    ('Garwood', NULL, 229, 'Bahia', 11),
    ('Tonnie', 141, 168, 'Fluminense', 14),
    ('Emelen', 70, NULL, 'Bahia', 5),
    ('Micah', 86, 83, 'Palmeiras', 4),
    ('Paddie', 94, 87, 'Atlético Mineiro', 13),
    ('Si', NULL, NULL, 'Grêmio', 15),
    ('Franz', 134, NULL, 'Goiás', 15),
    ('Hollis', NULL, NULL, 'Vasco', 14),
    ('Sanders', 42, 155, 'Vasco', 11),
    ('Diarmid', 33, 122, 'Fluminense', 10),
    ('Benjie', NULL, NULL, 'Santos', 13),
    ('Redd', NULL, NULL, 'Avaí', 7),
    ('Dare', 56, NULL, 'Cruzeiro', 7),
    ('Reinaldo', 128, 208, 'Ceará', 10),
    ('Efren', NULL, NULL, 'Fortaleza', 5),
    ('Hartley', NULL, NULL, 'Palmeiras', 8),
    ('Fonzie', NULL, NULL, 'Flamengo', 15),
    ('Rog', NULL, NULL, 'Palmeiras', 3),
    ('Serge', NULL, 138, 'Grêmio', 1),
    ('De witt', NULL, NULL, 'Ceará', 10),
    ('Garvy', 69, 185, 'Santos', 7),
    ('Tymon', 147, 65, 'Athletico Paranaense', 5),
    ('Humphrey', 95, NULL, 'Sport Recife', 14),
    ('Ciro', 104, 186, 'Fortaleza', 8),
    ('Pierson', 27, NULL, 'Chapecoense', 2),
    ('Sayers', NULL, 86, 'Fluminense', 15),
    ('Anton', 124, NULL, 'Palmeiras', 11),
    ('Skell', 36, NULL, 'Grêmio', 13),
    ('Davin', 2, 207, 'Bahia', 8),
    ('Ham', NULL, NULL, 'Grêmio', 5),
    ('Brenden', 65, 69, 'Sport Recife', 7),
    ('Brod', 83, NULL, 'Bahia', 1),
    ('Jerrold', 71, 196, 'Botafogo', 10),
    ('Hilary', NULL, NULL, 'Palmeiras', 11),
    ('Antonio', 9, NULL, 'Botafogo', 4),
    ('Garik', NULL, NULL, 'Vasco', 15),
    ('Taddeusz', NULL, NULL, 'Athletico Paranaense', 9),
    ('Zed', NULL, 158, 'Botafogo', 11),
    ('Rodney', NULL, NULL, 'Palmeiras', 7),
    ('Cad', 12, 146, 'Vasco', 1),
    ('Godfree', NULL, 172, 'Corinthians', 5),
    ('Barny', 89, 80, 'Palmeiras', 4),
    ('Tadio', 51, 95, 'Bahia', 5),
    ('Boigie', 62, 221, 'Flamengo', 14),
    ('Byrom', 26, NULL, 'Chapecoense', 1),
    ('Leonerd', NULL, 113, 'Flamengo', 12),
    ('Kennedy', 96, NULL, 'Sport Recife', 8),
    ('Nestor', 128, 81, 'Vasco', 7),
    ('Shea', NULL, 130, 'Flamengo', 7),
    ('Eduino', NULL, NULL, 'Avaí', 2),
    ('Teddy', 59, 196, 'Bahia', 12),
    ('Sidnee', NULL, NULL, 'Grêmio', 2),
    ('Staford', NULL, NULL, 'Goiás', 4),
    ('Phillipp', NULL, NULL, 'Fluminense', 4),
    ('Edlin', 16, NULL, 'Atlético Mineiro', 3),
    ('Elliott', NULL, NULL, 'Botafogo', 3),
    ('Mohandas', NULL, NULL, 'Fluminense', 4),
    ('Maynard', 28, NULL, 'Bahia', 8),
    ('Denney', 150, 172, 'São Paulo', 12),
    ('Anton', 69, 167, 'Grêmio', 11),
    ('Chaddy', NULL, 205, 'Botafogo', 12),
    ('Thom', 46, 182, 'Bahia', 8),
    ('Quintus', 112, NULL, 'Fluminense', 7),
    ('Ray', NULL, NULL, 'Corinthians', 15),
    ('Kippie', 31, 190, 'Palmeiras', 9),
    ('Bruis', 33, NULL, 'Athletico Paranaense', 5),
    ('Ado', 119, NULL, 'Palmeiras', 2),
    ('Andras', NULL, NULL, 'Vasco', 7),
    ('Gawen', NULL, 249, 'Fluminense', 12),
    ('Teodoro', NULL, 148, 'São Paulo', 13),
    ('Barnie', NULL, 74, 'Corinthians', 11),
    ('Horace', NULL, 223, 'Chapecoense', 5),
    ('Humfried', 69, 153, 'Vasco', 4),
    ('Elliott', NULL, 216, 'Botafogo', 10),
    ('Lucius', NULL, NULL, 'Grêmio', 1),
    ('Johnny', NULL, 118, 'Chapecoense', 7),
    ('Dewain', NULL, NULL, 'Chapecoense', 5),
    ('Robinet', 147, NULL, 'São Paulo', 15),
    ('Boony', NULL, NULL, 'Palmeiras', 6),
    ('Gery', NULL, 188, 'Santos', 9),
    ('Frasco', 145, NULL, 'Corinthians', 2),
    ('Pyotr', 136, NULL, 'Botafogo', 8),
    ('Felic', 36, 235, 'Flamengo', 2),
    ('Jayme', 131, NULL, 'Internacional', 2),
    ('Jard', 136, NULL, 'Bahia', 14),
    ('Ariel', 22, NULL, 'Ceará', 7),
    ('Muhammad', 74, NULL, 'Internacional', 10),
    ('Saunder', NULL, NULL, 'Internacional', 7),
    ('Burke', NULL, 207, 'Santos', 2),
    ('Murdock', NULL, 129, 'Internacional', 5),
    ('Hunt', 41, 111, 'Goiás', 12),
    ('Olav', 46, 189, 'Ceará', 12),
    ('Abel', 6, 90, 'Palmeiras', 12),
    ('Bondon', 8, 248, 'Palmeiras', 8),
    ('Thorin', NULL, NULL, 'Grêmio', 2),
    ('Pincas', NULL, 244, 'Palmeiras', 9),
    ('Maurizio', 77, 77, 'Corinthians', 12),
    ('Mark', NULL, 139, 'Atlético Mineiro', 7),
    ('Lane', 135, NULL, 'Grêmio', 5),
    ('Rogerio', 11, NULL, 'Avaí', 10),
    ('Kendall', NULL, 162, 'Avaí', 10),
    ('Giulio', 80, NULL, 'Cruzeiro', 4),
    ('Braden', NULL, NULL, 'Ceará', 15),
    ('Sven', 122, NULL, 'Sport Recife', 5),
    ('Hayward', 11, 215, 'Cruzeiro', 8),
    ('Hilliard', 147, 95, 'Fluminense', 11),
    ('Barnard', 99, 230, 'Avaí', 7),
    ('Iver', NULL, 86, 'Fortaleza', 5),
    ('Orton', 129, NULL, 'Atlético Mineiro', 15),
    ('Casar', NULL, 173, 'Cruzeiro', 14),
    ('Sydney', NULL, 149, 'Sport Recife', 7),
    ('Kenneth', NULL, 107, 'Athletico Paranaense', 3),
    ('Cozmo', NULL, 224, 'Chapecoense', 15),
    ('Fax', 49, NULL, 'São Paulo', 6),
    ('Ryley', NULL, 169, 'Bahia', 11),
    ('Giusto', NULL, 71, 'Sport Recife', 7),
    ('Chico', 20, 196, 'Santos', 11),
    ('Jerrold', NULL, NULL, 'Athletico Paranaense', 3),
    ('Diego', 18, NULL, 'Chapecoense', 6),
    ('Frederico', NULL, NULL, 'Bahia', 1),
    ('Brennan', 50, NULL, 'Goiás', 1),
    ('Byrom', NULL, NULL, 'Internacional', 11),
    ('Wallache', NULL, NULL, 'Vasco', 13),
    ('Ruby', NULL, NULL, 'Bahia', 1),
    ('Garry', NULL, NULL, 'Fluminense', 4),
    ('Kipper', 142, 197, 'Bahia', 5),
    ('Bing', NULL, NULL, 'Cruzeiro', 5),
    ('Ignatius', 128, NULL, 'Fluminense', 4),
    ('Barnett', NULL, 73, 'Cruzeiro', 4),
    ('Marlowe', 18, 182, 'Bahia', 14),
    ('Linc', 123, 217, 'Ceará', 4),
    ('Alfie', 67, 228, 'Cruzeiro', 1),
    ('Piotr', 23, 178, 'Internacional', 9),
    ('Eb', 75, 145, 'Atlético Mineiro', 7),
    ('Claudius', 29, 214, 'Palmeiras', 9),
    ('Goran', 56, NULL, 'Botafogo', 13),
    ('Correy', 71, NULL, 'Ceará', 9),
    ('Lawry', 139, 107, 'Bahia', 5),
    ('Evelyn', NULL, 142, 'Santos', 15),
    ('Anders', NULL, 176, 'Athletico Paranaense', 8),
    ('Munroe', 149, NULL, 'Internacional', 2),
    ('Yorgo', NULL, NULL, 'Cruzeiro', 9),
    ('Dave', NULL, NULL, 'Vasco', 7),
    ('Sandy', 32, 194, 'Palmeiras', 15),
    ('Town', 85, NULL, 'Sport Recife', 1),
    ('Foster', NULL, NULL, 'Palmeiras', 11),
    ('Maury', 135, 189, 'Bahia', 5),
    ('Roth', 60, NULL, 'Atlético Mineiro', 10),
    ('Siegfried', NULL, 149, 'Cruzeiro', 6),
    ('Frederich', NULL, NULL, 'Fluminense', 2),
    ('Noak', 112, 141, 'São Paulo', 7),
    ('Ellerey', NULL, 143, 'Grêmio', 15),
    ('Elihu', NULL, NULL, 'Ceará', 14),
    ('Holly', 111, 237, 'Athletico Paranaense', 10),
    ('Peder', 95, NULL, 'Goiás', 13),
    ('Walsh', 81, 182, 'Corinthians', 2),
    ('Leicester', NULL, NULL, 'Santos', 13),
    ('Godfrey', 83, NULL, 'Fortaleza', 7),
    ('Arie', NULL, NULL, 'Fortaleza', 2),
    ('Dev', NULL, 181, 'Athletico Paranaense', 1),
    ('Colas', 120, NULL, 'Atlético Mineiro', 5),
    ('Micah', 41, 152, 'São Paulo', 2),
    ('Spencer', 13, NULL, 'Fortaleza', 15),
    ('Silvio', NULL, 162, 'Fluminense', 8),
    ('Wang', 94, NULL, 'Cruzeiro', 11),
    ('Allard', 100, 197, 'Goiás', 9),
    ('Tucky', NULL, NULL, 'Goiás', 13),
    ('Sid', 88, NULL, 'Goiás', 15),
    ('Christiano', 20, 81, 'Atlético Mineiro', 10),
    ('Jerry', NULL, NULL, 'Botafogo', 8),
    ('Thorndike', NULL, 170, 'Flamengo', 5),
    ('Yul', 49, NULL, 'Corinthians', 9),
    ('Ban', 17, 236, 'Atlético Mineiro', 3),
    ('Felice', 49, NULL, 'Athletico Paranaense', 13),
    ('Claiborne', NULL, NULL, 'Flamengo', 4),
    ('Kasper', 82, NULL, 'Athletico Paranaense', 1),
    ('Renaldo', 148, NULL, 'Ceará', 3),
    ('Valentino', 128, NULL, 'São Paulo', 12),
    ('Rockie', NULL, NULL, 'Fluminense', 8),
    ('Gerard', NULL, 209, 'Flamengo', 8),
    ('Alden', NULL, 197, 'Cruzeiro', 3),
    ('Valentin', 72, NULL, 'Botafogo', 15),
    ('Tobie', NULL, 115, 'Palmeiras', 11),
    ('Paolo', NULL, NULL, 'Chapecoense', 9),
    ('Weider', NULL, 156, 'Corinthians', 3),
    ('Eugen', NULL, NULL, 'Athletico Paranaense', 9),
    ('Christopher', 8, 74, 'Ceará', 5),
    ('Arney', NULL, 94, 'Fortaleza', 8),
    ('Bayard', NULL, NULL, 'Ceará', 9),
    ('Kile', 85, 108, 'Palmeiras', 8),
    ('Ramon', 25, 227, 'Botafogo', 13),
    ('Tobiah', 124, 82, 'Atlético Mineiro', 5),
    ('Graig', NULL, 121, 'Sport Recife', 7),
    ('Curr', NULL, NULL, 'Internacional', 3),
    ('Jaymie', 20, 141, 'Fluminense', 14),
    ('Kylie', NULL, 217, 'Cruzeiro', 7),
    ('Borden', NULL, NULL, 'Vasco', 11),
    ('Arturo', NULL, 98, 'Botafogo', 1),
    ('Devin', NULL, 193, 'Sport Recife', 12),
    ('Teodoor', NULL, NULL, 'Fluminense', 12),
    ('Isak', NULL, 207, 'Corinthians', 3),
    ('Pryce', NULL, 128, 'Vasco', 7),
    ('Iain', 114, NULL, 'Vasco', 2),
    ('Michele', 137, NULL, 'Atlético Mineiro', 8),
    ('Munmro', NULL, NULL, 'Avaí', 9),
    ('Clayborn', NULL, 72, 'Fluminense', 2),
    ('Lynn', 4, 233, 'Grêmio', 15),
    ('Darill', NULL, NULL, 'Bahia', 5),
    ('Benyamin', 95, 70, 'Athletico Paranaense', 4),
    ('Jocko', NULL, NULL, 'São Paulo', 8),
    ('Louie', NULL, 131, 'Flamengo', 9),
    ('Friedrick', NULL, NULL, 'Internacional', 12),
    ('Vassili', 122, 208, 'Chapecoense', 6),
    ('Irwinn', 141, 170, 'Bahia', 9),
    ('Lanie', NULL, NULL, 'Ceará', 4),
    ('Bartolomeo', 7, 102, 'Ceará', 11),
    ('Moses', NULL, NULL, 'Botafogo', 11),
    ('Guntar', NULL, 78, 'Athletico Paranaense', 12),
    ('Burtie', NULL, NULL, 'Fluminense', 13),
    ('Bancroft', NULL, 193, 'Corinthians', 1),
    ('Leonhard', 77, 239, 'Avaí', 13),
    ('Regan', NULL, 92, 'Palmeiras', 10),
    ('Richmound', NULL, 193, 'Avaí', 3),
    ('Clementius', 63, NULL, 'Fluminense', 5),
    ('Tarrance', 149, NULL, 'Palmeiras', 8),
    ('Milt', NULL, 188, 'Internacional', 13),
    ('Luther', NULL, NULL, 'Palmeiras', 1),
    ('Virgil', NULL, 177, 'Grêmio', 11),
    ('Markus', 109, 97, 'Flamengo', 11),
    ('Nero', 127, 129, 'Goiás', 2),
    ('Walton', 81, NULL, 'Fluminense', 3),
    ('Michel', NULL, 75, 'Sport Recife', 12),
    ('Efrem', NULL, NULL, 'Palmeiras', 3),
    ('Lisle', NULL, 140, 'Chapecoense', 12),
    ('Stuart', 141, 114, 'Cruzeiro', 8),
    ('Rafael', NULL, NULL, 'Fluminense', 7),
    ('Amory', NULL, NULL, 'Santos', 15),
    ('Ikey', 145, NULL, 'Santos', 5),
    ('Quinn', NULL, 87, 'Internacional', 7),
    ('Abdul', NULL, 235, 'Botafogo', 1),
    ('Chevalier', NULL, NULL, 'Vasco', 7),
    ('Nickey', NULL, 184, 'Vasco', 2),
    ('Nikos', 54, 228, 'Atlético Mineiro', 10),
    ('Marcus', NULL, 136, 'Athletico Paranaense', 10),
    ('Micah', NULL, NULL, 'Vasco', 1),
    ('Forrester', NULL, NULL, 'Corinthians', 2),
    ('Jed', 99, NULL, 'Bahia', 12),
    ('Quintin', NULL, NULL, 'Bahia', 5),
    ('Gerald', 33, 229, 'Chapecoense', 15),
    ('Skye', 50, 77, 'Ceará', 8),
    ('Maurise', 54, NULL, 'Atlético Mineiro', 7),
    ('Parry', 148, NULL, 'Palmeiras', 10),
    ('Cobb', NULL, 170, 'Cruzeiro', 11),
    ('Abe', NULL, NULL, 'São Paulo', 2),
    ('Shaine', 27, 243, 'Ceará', 12),
    ('Roddy', NULL, 94, 'Grêmio', 13),
    ('Stephen', 27, NULL, 'Avaí', 4),
    ('Rafi', NULL, NULL, 'Flamengo', 7),
    ('Bancroft', 123, NULL, 'Avaí', 12),
    ('Buck', NULL, NULL, 'São Paulo', 2),
    ('Leonard', NULL, 199, 'Fortaleza', 6),
    ('Huey', NULL, 230, 'Botafogo', 1),
    ('Amble', NULL, 142, 'Chapecoense', 3),
    ('Tore', 2, NULL, 'Goiás', 5),
    ('Wildon', NULL, 193, 'Sport Recife', 7),
    ('Coop', NULL, NULL, 'Sport Recife', 10),
    ('Raddy', NULL, 72, 'Goiás', 12),
    ('Ricki', 70, NULL, 'Athletico Paranaense', 8),
    ('Zelig', 51, 207, 'Fluminense', 6),
    ('Alain', NULL, 132, 'Cruzeiro', 11),
    ('Raymond', NULL, NULL, 'Cruzeiro', 5),
    ('Lev', NULL, NULL, 'Atlético Mineiro', 6),
    ('Thorn', NULL, 199, 'Ceará', 7),
    ('Meyer', 64, NULL, 'Corinthians', 6),
    ('Thadeus', NULL, 222, 'Goiás', 9),
    ('Matty', NULL, 184, 'Fluminense', 4),
    ('Land', 53, NULL, 'São Paulo', 6),
    ('Willey', NULL, NULL, 'Atlético Mineiro', 3),
    ('Valentine', NULL, 96, 'Sport Recife', 2),
    ('Durante', 112, NULL, 'Fluminense', 1),
    ('Kenon', 47, 142, 'Santos', 11),
    ('Arlin', 60, 163, 'Grêmio', 14),
    ('Gordy', NULL, NULL, 'Avaí', 10),
    ('Wesley', 13, 159, 'Santos', 11),
    ('Abbie', 147, NULL, 'Athletico Paranaense', 4),
    ('Griffith', 36, NULL, 'Corinthians', 10),
    ('Kingston', 145, 135, 'Bahia', 5),
    ('Brendan', NULL, NULL, 'Fluminense', 9),
    ('Shelton', NULL, 236, 'Botafogo', 13),
    ('Waylen', NULL, 150, 'Bahia', 1),
    ('Cortie', NULL, 192, 'Vasco', 13),
    ('Scot', NULL, NULL, 'Vasco', 11),
    ('Cam', 136, 229, 'Athletico Paranaense', 12),
    ('Kipp', NULL, 134, 'Flamengo', 4),
    ('Waite', NULL, NULL, 'Cruzeiro', 2),
    ('Ximenes', NULL, NULL, 'Sport Recife', 8),
    ('Marlon', NULL, 160, 'Corinthians', 14),
    ('Maison', NULL, NULL, 'Flamengo', 8),
    ('Christoforo', NULL, 186, 'Flamengo', 15),
    ('Darn', NULL, NULL, 'Fluminense', 8),
    ('Wittie', NULL, 229, 'Goiás', 11),
    ('Lancelot', NULL, 171, 'Atlético Mineiro', 9),
    ('Denny', 68, NULL, 'Internacional', 15),
    ('Aldus', 148, NULL, 'Avaí', 12),
    ('Johannes', NULL, NULL, 'Grêmio', 10),
    ('Roderich', 92, NULL, 'Vasco', 10),
    ('Erny', 64, 128, 'Ceará', 11),
    ('Sherwin', 40, NULL, 'São Paulo', 1),
    ('Niall', NULL, 145, 'Athletico Paranaense', 2),
    ('Roger', NULL, NULL, 'Athletico Paranaense', 8),
    ('Shelden', NULL, NULL, 'Avaí', 9),
    ('Neddy', NULL, NULL, 'Fluminense', 15),
    ('Wallis', 71, 159, 'Avaí', 13),
    ('Trey', NULL, NULL, 'Corinthians', 5),
    ('Mikol', NULL, NULL, 'Fortaleza', 4),
    ('Rorke', NULL, 189, 'Fluminense', 4),
    ('Vince', 28, 120, 'Fortaleza', 9),
    ('Curr', 115, NULL, 'Grêmio', 11),
    ('Chev', 137, 248, 'Santos', 7),
    ('Stanford', 125, 228, 'Fortaleza', 12),
    ('Cornelius', NULL, 244, 'Bahia', 1),
    ('Herby', 92, 212, 'Fluminense', 14),
    ('Pooh', NULL, NULL, 'Goiás', 3),
    ('Stanwood', NULL, NULL, 'Ceará', 10),
    ('Abey', NULL, 154, 'Atlético Mineiro', 8),
    ('Ryley', NULL, NULL, 'Cruzeiro', 5),
    ('Vern', 112, 111, 'Sport Recife', 6),
    ('Neill', 136, 84, 'Avaí', 13),
    ('Mikol', NULL, 76, 'Corinthians', 10),
    ('Mischa', NULL, 235, 'Cruzeiro', 5),
    ('Theodoric', NULL, NULL, 'Chapecoense', 10),
    ('Sigmund', 73, NULL, 'São Paulo', 11),
    ('Finn', NULL, 153, 'Fluminense', 9),
    ('Reidar', 73, 222, 'Corinthians', 7),
    ('Hurlee', 141, 70, 'Avaí', 14),
    ('Averell', 95, 80, 'Flamengo', 14),
    ('Antoine', NULL, NULL, 'Atlético Mineiro', 13),
    ('Benji', 137, NULL, 'Corinthians', 1),
    ('Leonidas', 107, 145, 'Grêmio', 1),
    ('Onofredo', NULL, 181, 'Avaí', 9),
    ('Marwin', 25, NULL, 'Bahia', 14),
    ('Reuben', 108, 147, 'Goiás', 14),
    ('Lucas', 140, NULL, 'Bahia', 10),
    ('Dalt', 103, NULL, 'Goiás', 8),
    ('Jared', NULL, NULL, 'Botafogo', 8),
    ('Brewer', NULL, NULL, 'Ceará', 1),
    ('Owen', NULL, NULL, 'Fortaleza', 7),
    ('Briant', NULL, NULL, 'Atlético Mineiro', 7),
    ('Alvan', 134, NULL, 'Sport Recife', 15),
    ('Davie', NULL, 247, 'Sport Recife', 10),
    ('Kenny', NULL, NULL, 'Fortaleza', 7),
    ('Abey', NULL, NULL, 'Ceará', 9),
    ('Charley', NULL, 108, 'Grêmio', 11),
    ('Tedie', 72, 110, 'Sport Recife', 5),
    ('Rolando', 30, NULL, 'Flamengo', 10),
    ('Zach', 9, 124, 'Atlético Mineiro', 11),
    ('Gaspard', NULL, NULL, 'Goiás', 7),
    ('Delmar', 17, NULL, 'Fluminense', 15),
    ('Gregory', 144, NULL, 'Vasco', 2),
    ('Carroll', NULL, NULL, 'Corinthians', 15),
    ('Vassili', NULL, NULL, 'Fortaleza', 11),
    ('Brooks', NULL, 179, 'Palmeiras', 4),
    ('Douglass', NULL, NULL, 'Palmeiras', 9),
    ('Ozzy', NULL, NULL, 'Internacional', 13),
    ('Reamonn', NULL, 249, 'Palmeiras', 7),
    ('Ebeneser', 100, NULL, 'São Paulo', 15),
    ('Antonino', 69, NULL, 'Goiás', 5),
    ('Mahmud', 83, NULL, 'Flamengo', 12),
    ('Luther', 129, 189, 'Flamengo', 6),
    ('Joseito', 46, NULL, 'Flamengo', 5),
    ('Vasili', 144, 184, 'São Paulo', 15),
    ('Bennie', NULL, NULL, 'Cruzeiro', 14),
    ('Duncan', 50, NULL, 'Vasco', 12),
    ('Raymond', 20, NULL, 'Bahia', 10),
    ('Brocky', 37, NULL, 'Vasco', 11),
    ('Andras', NULL, NULL, 'Internacional', 3),
    ('Felike', 143, 233, 'Flamengo', 2),
    ('Rollins', 58, NULL, 'Athletico Paranaense', 10),
    ('Jeromy', 12, NULL, 'Botafogo', 12),
    ('Ed', 46, NULL, 'Santos', 3),
    ('Yancy', 26, NULL, 'Avaí', 5),
    ('Alfons', 145, 78, 'Athletico Paranaense', 4),
    ('Roberto', 145, NULL, 'Vasco', 6),
    ('Hanan', NULL, NULL, 'Goiás', 5),
    ('Aristotle', NULL, NULL, 'São Paulo', 1),
    ('Pen', 111, NULL, 'Internacional', 5),
    ('Kristofor', 121, 232, 'Fortaleza', 12),
    ('Hilarius', NULL, NULL, 'Internacional', 13),
    ('Hashim', 139, 179, 'Fortaleza', 1),
    ('Jo', 11, 184, 'Corinthians', 9),
    ('Werner', NULL, 119, 'Corinthians', 8),
    ('Warren', NULL, 107, 'Fluminense', 9),
    ('Aloysius', NULL, NULL, 'Botafogo', 5),
    ('Lemmy', NULL, NULL, 'Goiás', 8),
    ('Reube', 91, NULL, 'Cruzeiro', 9),
    ('Kent', NULL, 129, 'Atlético Mineiro', 4),
    ('Virgil', NULL, 130, 'Athletico Paranaense', 6),
    ('Gasparo', 92, NULL, 'Cruzeiro', 5),
    ('Constantine', NULL, 111, 'Vasco', 1),
    ('Alphonso', NULL, NULL, 'São Paulo', 15),
    ('Claudius', NULL, NULL, 'Santos', 11),
    ('Reider', 103, 146, 'Botafogo', 10),
    ('Mauricio', 6, 118, 'Fortaleza', 15),
    ('Thain', 127, NULL, 'Grêmio', 13),
    ('Glenn', NULL, 119, 'Grêmio', 1),
    ('Ferris', 90, 179, 'Chapecoense', 13),
    ('Jarvis', 36, 222, 'Cruzeiro', 12),
    ('Douglass', 44, 147, 'Sport Recife', 11),
    ('Orrin', 144, NULL, 'Fluminense', 13),
    ('Tonnie', 41, NULL, 'Bahia', 4),
    ('Martainn', 97, NULL, 'Avaí', 10),
    ('Garrott', 144, NULL, 'Botafogo', 4),
    ('Paco', NULL, NULL, 'Palmeiras', 2),
    ('Maximilianus', NULL, 210, 'Santos', 1),
    ('Derek', 31, 189, 'Grêmio', 4),
    ('Foster', NULL, NULL, 'Avaí', 14),
    ('Cy', NULL, 112, 'Chapecoense', 12),
    ('Dunstan', NULL, 227, 'Avaí', 5),
    ('Byran', NULL, NULL, 'Corinthians', 13),
    ('Monro', NULL, NULL, 'Ceará', 3),
    ('Kristofor', 98, NULL, 'Vasco', 9),
    ('Julian', 149, 94, 'Vasco', 8),
    ('Ariel', NULL, 209, 'Corinthians', 2),
    ('Findley', 114, 155, 'Botafogo', 2),
    ('Thorn', 135, NULL, 'Corinthians', 3),
    ('Gerardo', 147, 94, 'Goiás', 2),
    ('Miguel', NULL, 185, 'Flamengo', 6),
    ('Elmo', 17, NULL, 'Chapecoense', 3),
    ('Irwin', NULL, NULL, 'Bahia', 13),
    ('Bernardo', NULL, NULL, 'Grêmio', 14),
    ('Janek', NULL, NULL, 'Ceará', 11),
    ('Faulkner', 82, NULL, 'Avaí', 8),
    ('Shepperd', NULL, NULL, 'Fluminense', 10),
    ('Bendick', 23, 184, 'Flamengo', 6),
    ('Dukey', NULL, 153, 'Grêmio', 9),
    ('Raymund', NULL, 99, 'Avaí', 5),
    ('Enoch', 84, NULL, 'Palmeiras', 7),
    ('Yorke', 113, NULL, 'Ceará', 8),
    ('Mort', NULL, 182, 'Grêmio', 14),
    ('Jedediah', NULL, 211, 'Vasco', 9),
    ('Baxie', 70, 69, 'Palmeiras', 14),
    ('Barris', NULL, 120, 'Vasco', 15),
    ('Beau', NULL, NULL, 'Internacional', 1),
    ('Colin', 40, 97, 'Santos', 8),
    ('Torrin', NULL, 197, 'Atlético Mineiro', 13),
    ('Dante', 87, NULL, 'São Paulo', 9),
    ('Jude', NULL, NULL, 'Vasco', 2),
    ('Lionel', NULL, 239, 'Flamengo', 3),
    ('Nick', 92, NULL, 'Flamengo', 7),
    ('Hansiain', NULL, 183, 'Flamengo', 4),
    ('Richardo', 22, 77, 'Internacional', 6),
    ('Rodger', NULL, NULL, 'Atlético Mineiro', 1),
    ('Ezekiel', 38, 242, 'Fluminense', 10),
    ('Yves', 28, 165, 'Ceará', 4),
    ('Lester', 87, 227, 'Cruzeiro', 9),
    ('Gill', 118, 201, 'Ceará', 5),
    ('Araldo', 65, NULL, 'Internacional', 7),
    ('Leon', 79, 204, 'Sport Recife', 9),
    ('Luke', 84, NULL, 'Grêmio', 4),
    ('Johann', NULL, 241, 'Fortaleza', 6),
    ('Sammie', NULL, NULL, 'Santos', 14),
    ('Jacobo', NULL, 193, 'Goiás', 2),
    ('Conant', NULL, 112, 'Sport Recife', 11),
    ('Andres', 88, NULL, 'Santos', 14),
    ('Biron', NULL, 183, 'Grêmio', 11),
    ('Boy', 80, 187, 'Avaí', 4),
    ('Gordon', 148, NULL, 'Avaí', 7),
    ('Flin', NULL, NULL, 'Santos', 9),
    ('Kip', NULL, NULL, 'Chapecoense', 3),
    ('Maurizio', NULL, 146, 'Palmeiras', 10),
    ('Borden', NULL, NULL, 'Palmeiras', 15),
    ('Hamnet', NULL, 157, 'Atlético Mineiro', 7),
    ('Ring', NULL, NULL, 'Sport Recife', 7);