CREATE TABLE IF NOT EXISTS tb_gamemode
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    formation_name VARCHAR(50)                              NOT NULL,
    description    TEXT                                     DEFAULT NULL,

    PRIMARY KEY (id),
    UNIQUE (formation_name),
    CHECK (LENGTH(description) <= 2000)
);
