CREATE TABLE IF NOT EXISTS tb_game_mode
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    formation_name VARCHAR(50)                              NOT NULL,
    description    TEXT                                     DEFAULT NULL,

    PRIMARY KEY (id),
    CHECK (LENGTH(description) <= 2000)
);
