CREATE TABLE IF NOT EXISTS tb_player
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(30)                             NOT NULL,
    age         INT                                     DEFAULT NULL,
    height      INT                                     DEFAULT NULL,
    team        VARCHAR(30)                             NOT NULL,
    position_id BIGINT                                  NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY (position_id) REFERENCES tb_position (id),
    CHECK ((age >= 1) AND (age <= 150)),
    CHECK ((height >= 65) AND (height <= 250))
);
